name: bus_finder
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^8.1.4
  provider: ^6.1.1
  pull_to_refresh: ^2.0.0
  http: ^1.2.0
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.2.4
  flutter_lints: ^2.0.0
  syncfusion_flutter_datepicker: ^24.2.5
  intl: ^0.19.0

flutter:


  uses-material-design: true

